name: CI

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: refresh apt repo
      run: sudo apt-get update
    - name: install auto...
      run: sudo apt-get install autoconf automake libtool libsndfile-dev -y
    - name: configure
      run: autoreconf -i && ./configure
    - name: build
      run: make
    - name: exists
      run: ls src/.libs/libfvad.so.0.0.0
  
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install auto...
      run: brew install autoconf automake libtool libsndfile pkg-config
    - name: configure
      run: autoreconf -i && ./configure
    - name: build
      run: make
    - name: publish
      run: ls src/.libs/libfvad.0.dylib

  build-windows-32bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: refresh apt repo
      run: sudo apt-get update
    - name: install auto...
      run: sudo apt-get install autoconf automake libtool libsndfile-dev mingw-w64 -y
    - name: configure
      run: autoreconf -i && ./configure --host=i686-w64-mingw32
    - name: build
      run: make
    - name: exists
      run: ls src/.libs/libfvad-0.dll

  build-windows-64bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: refresh apt repo
      run: sudo apt-get update
    - name: install auto...
      run: sudo apt-get install autoconf automake libtool libsndfile-dev mingw-w64 -y
    - name: configure
      run: autoreconf -i && ./configure --host=x86_64-w64-mingw32
    - name: build
      run: make
    - name: exists
      run: ls src/.libs/libfvad-0.dll
